const S={x:0,y:0,money:100,score:0,relationship:0,car:false,companion:false};
const $=x=>document.getElementById(x), toast=$("toast"),world=$("world");
function update(){ $("money").textContent=S.money;$("score").textContent=S.score;$("rel").textContent=S.relationship;$("relBar").style.width=S.relationship+"%";$("player").style.display=S.car?"none":"block";$("car").style.display=S.car?"block":"none";$("world").style.transform=`translate(${S.x}px,${S.y}px) scale(1.04)`;}
function say(t){toast.textContent=t;clearTimeout(window.t);window.t=setTimeout(()=>toast.textContent="MAD CITY HD",2600)}
function move(x,y){S.x+=x;S.y+=y;S.score++;update()}
function save(){localStorage.setItem("MAD_CITY_HD_SAVE",JSON.stringify(S));say("💾 Progress saved!")}
function load(){let d=localStorage.getItem("MAD_CITY_HD_SAVE");if(!d)return say("No saved game yet.");Object.assign(S,JSON.parse(d));update();say("✅ Progress loaded!")}
function talk(){S.relationship=Math.min(100,S.relationship+5);say("💬 Asha: Nice to see you!");save();update()}
function gift(){if(S.money<20)return say("💰 You need $20.");S.money-=20;S.relationship=Math.min(100,S.relationship+15);say("🎁 Asha liked the gift! +15%");save();update()}
function follow(){if(S.relationship<20)return say("❤️ Reach 20% relationship first.");S.companion=!S.companion;say(S.companion?"🤝 Asha is your companion!":"👋 Companion mode off.");save()}
document.addEventListener("keydown",e=>{let k=e.key.toLowerCase();if(k=="w"||k=="arrowup")move(0,4);if(k=="s"||k=="arrowdown")move(0,-4);if(k=="a"||k=="arrowleft")move(4,0);if(k=="d"||k=="arrowright")move(-4,0);if(k=="e"){S.car=!S.car;update();say(S.car?"🚗 Driving mode":"👤 Walking mode")}});document.querySelectorAll("[data-k]").forEach(b=>b.onpointerdown=()=>{let k=b.dataset.k;if(k=="up")move(0,4);if(k=="down")move(0,-4);if(k=="left")move(4,0);if(k=="right")move(-4,0)});$("vehicle").onclick=()=>{S.car=!S.car;update()};$("save").onclick=save;$("load").onclick=load;$("talk").onclick=talk;$("gift").onclick=gift;$("follow").onclick=follow;$("new").onclick=()=>{Object.assign(S,{x:0,y:0,money:100,score:0,relationship:0,car:false,companion:false});update();say("🆕 New game")};update();setTimeout(()=>$("loading").remove(),1300);